### ISSUE TITLE
Use `notify` in JavaScript

### ISSUE THREAD

**Issue by goSeeFuture** [markmead/alpinejs-notify#4]
`alpinejs-notifications` is a great plugin, I'm currently trying to apply it in my project and would like to trigger notification alerts via JavaScript, however I didn't find a specific way to do it in the plugin, I consulted [AlpineJs discussions](https://github.com/alpinejs/alpine/discussions/3894) and was advised that it's best to do it on the plugin side.  and got the advice that it's best to solve it on the plugin side.

Thanks again to the plugin author for helping me simplify my work.

**Comment by markmead** [comment]
Not something the plugin supports and isn't something I plan to add. Happy for you to fork the repository and make your own version with that support though!
